version: "3.9"

services:
  frontend:
    image: ${DOCKER_USERNAME}/chat-frontend:latest
    container_name: chat-app

    # CHANGED: Automatically restart container
    restart: unless-stopped

    # CHANGED: Read environment variables from EC2
    env_file:
      - /home/ubuntu/.env

    # CHANGED: Expose Next.js
    ports:
      - "3000:3000"